// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMf3y8P1qUmxiZoK4bio7dicek7RYhLls',
    appId: '1:901563232876:web:28fea77d1f553262f61e49',
    messagingSenderId: '901563232876',
    projectId: 'bitcoin-chat-12589',
    authDomain: 'bitcoin-chat-12589.firebaseapp.com',
    databaseURL: 'https://bitcoin-chat-12589-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bitcoin-chat-12589.appspot.com',
    measurementId: 'G-GTXS8KVLZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZwkPCzCZfKsC6T2qO5Jt0cwLBjNfmUOU',
    appId: '1:901563232876:android:39b23bdb87ec82d2f61e49',
    messagingSenderId: '901563232876',
    projectId: 'bitcoin-chat-12589',
    databaseURL: 'https://bitcoin-chat-12589-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bitcoin-chat-12589.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQbJVfrSDxOVixvICpPFQOpgZtFlsAQqM',
    appId: '1:901563232876:ios:3ffb612cc7148ee5f61e49',
    messagingSenderId: '901563232876',
    projectId: 'bitcoin-chat-12589',
    databaseURL: 'https://bitcoin-chat-12589-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bitcoin-chat-12589.appspot.com',
    iosClientId: '901563232876-qdcelnu02m6376qh6ei19o4c6plmv88l.apps.googleusercontent.com',
    iosBundleId: 'com.example.bitcoinChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQbJVfrSDxOVixvICpPFQOpgZtFlsAQqM',
    appId: '1:901563232876:ios:3ffb612cc7148ee5f61e49',
    messagingSenderId: '901563232876',
    projectId: 'bitcoin-chat-12589',
    databaseURL: 'https://bitcoin-chat-12589-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bitcoin-chat-12589.appspot.com',
    iosClientId: '901563232876-qdcelnu02m6376qh6ei19o4c6plmv88l.apps.googleusercontent.com',
    iosBundleId: 'com.example.bitcoinChat',
  );
}
